### ISSUE TITLE
Template for scan sheet

### ISSUE THREAD

**Issue by orduek** [LevyDecisionNeuroLab/pipeline#3]
Build a template for a simple csv (excel) file that has series number and name of task

**Comment by orduek** [comment]
In my view, a simple two-column file per subject will do. 
should look like:
SeriesNo | Name
1              | MPRAGE
2              | LOSS
etc.

**Comment by sophiakatzz** [comment]
I can take this

**Comment by sophiakatzz** [comment]
[template for RAID scan sheet.csv](https://github.com/LevyDecisionNeuroLab/pipeline/files/7997722/template.for.RAID.scan.sheet.csv)

**Comment by orduek** [comment]
LGTM!
Maybe add one "full" example as well. And also, make the filename more computer readable (so no spaces, only words and underscores)

**Comment by sophiakatzz** [comment]
[scan_sheet_template.csv](https://github.com/LevyDecisionNeuroLab/pipeline/files/7997789/scan_sheet_template.csv)

**Comment by orduek** [comment]
Template is solved. Closing issue.
